### ISSUE TITLE
Dot on numpad doesn't work, works only as delete regardless of numlock status

### ISSUE THREAD

**Issue by mhk13** [unixwork/xnedit#149]
When numlock is on, the dot button on the numpad doesn't type a period, but deletes the character next to cursor.

**Comment by unixwork** [comment]
Confirmed.

**Comment by unixwork** [comment]
The newest commit should fix this issue.

**Comment by mhk13** [comment]
Hi @unixwork,
I tried the new binaries, I think the issue is still there. the separator on the numpad is still working as delete for me.

**Comment by mhk13** [comment]
Thanks for the prompt reply Olaf, It says 1.6.1 (screenshot attached)
dot separator works in other applications as well, I'm using centos 7
![image](https://github.com/user-attachments/assets/2ed3de0a-327d-4497-bffc-10f164a24e92)

**Comment by mhk13** [comment]
Maybe it has something to do with the nedit.rc file? Do you think I should delete it?

**Comment by unixwork** [comment]
Yes, you can try to rename/delete the nedit.rc file.

It is also possible, that is has something to do with X resources. You can try to reset them with

    xrdb -query > xresources.bak
    echo | xrdb -load -
    xnedit

To restore the X resources: `xrdb -load xresources.bak`

**Comment by mhk13** [comment]
still not working for me unfortunately

**Comment by unixwork** [comment]
Which OS and desktop environment are you using?

**Comment by mhk13** [comment]
> Which OS and desktop environment are you using?

Apologies for the late response @unixwork .. got stuck in a project delivery and wasn't really checking mail 
I'm using Centos 7 EL7.x86_64, running xfce desktop env
In this current machine, numpad is not recognized in regular nedit except for the '5' button  when numpad is enabled. Maybe this is a key to reproducing the issue.
I've trued xnedit in another machine that doesn't have the numpad issue and the separator doesn't have an issue in this. maybe it's a motif version issue?

**Comment by unixwork** [comment]
I tried it on Oracle Linux 7, which should be basically the same as Centos 7, and it works. 

What is the output of `cat /etc/system-release`?

Also, if available, can you run the `xev` program and press the numpad separator key? This tool prints all X events to stdout, and it should contain something like 

    KeyRelease event, serial 37, synthetic NO, window 0x2600001,
        root 0x3ac, subw 0x0, time 398194, (-442,468), root:(749,1183),
        state 0x0, keycode 91 (keysym 0xff9f, KP_Delete), same_screen YES,
        XLookupString gives 0 bytes:
        XFilterEvent returns: False

**Comment by mhk13** [comment]
This is the system-release cat:
![image](https://github.com/user-attachments/assets/219d0a0e-3d4b-4bf4-b4a9-9fb043af6839)
and this is the xev result when I press the key:
![image](https://github.com/user-attachments/assets/69fce6ed-3f05-415f-be68-7899d9726342)
it's identified as KP_Decimal, i think the KP_delete is what it should do when the numpad lock is off.

**Comment by unixwork** [comment]
For me it is KP_Separator and KP_Decimal was not handled yet.

Can you try these binaries?

[xnedit-1.6.1-EL7_kp_decimal_fix.tar.gz](https://github.com/user-attachments/files/18439913/xnedit-1.6.1-EL7_kp_decimal_fix.tar.gz)

**Comment by mhk13** [comment]
works perfectly, many thanks!
Really appreciate it man
